apiVersion: v1
kind: Service
metadata:
  name: temporal-service
spec:
  selector:
    app: temporal-app
  type: LoadBalancer 
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31000